# This is a basic workflow to help you get started with Actions

name: aws_server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'terratest/aws/aws-instance/aws_instance_test.go'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd terratest/aws/aws-instance
          go mod init github.com/gruntwork-io/terratest/tree/master/modules/terraform
          go mod tidy
          go get github.com/gruntwork-io/terratest/modules/random
          go get github.com/gruntwork-io/terratest/modules/ssh@v0.37.5
          go get github.com/gruntwork-io/terratest/modules/terraform@v0.37.5
          go test
