# This is a basic workflow to help you get started with Actions

name: gce_server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'terraform/modules/google_compute_instance/**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GAC: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $GAC | -d > $RUNNER_TEMP/sa.json
          export $GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa.json
          cd terratest/gcp/compute-instance
          go mod init github.com/gruntwork-io/terratest/tree/master/modules/terraform
          go mod tidy
          go get github.com/gruntwork-io/terratest/modules/random
          go get github.com/gruntwork-io/terratest/modules/ssh@v0.37.5
          go get github.com/gruntwork-io/terratest/modules/terraform@v0.37.5
          go test
