name: hcloud test

on:
  
  workflow_dispatch:
jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - id: runner
        name: Start runner
        uses: andycockers/hcloud-actions-runner/start@0.0.5
        with:
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          type: type=github-hcloud-runner
          server_type: cx11
          location: fsn1
          network_id: "823122"
          github-token: ${{ secrets.GH_PAT }}
    outputs:
      instance-id: ${{ steps.runner.outputs.instance-id }}

  main:
   needs: start-runner
   runs-on: ${{ needs.start-runner.outputs.instance-id }}
   steps:
     - run: uname -a