name: hcloud test

on:
  
  workflow_dispatch:
jobs:
  start-runner:
    runs-on: ubuntu-latest
    outputs:
      instance-id: ${{ steps.runner.outputs.instance-id }}
    steps:
    - name: Checkout Terraform code
      uses: actions/checkout@v2
      with:
        repository: andycockers/hcloud-actions-runner
        token: ${{ secrets.GH_PAT }}
        path: hcloud-actions-runner

    - id: runner
      name: Start runner
      uses: andycockers/hcloud-actions-runner/start@v0.0.38
      with:
        hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        type: "type=github_hcloud_runner"
        server_type: cx11
        location: fsn1
        network_id: "823122"
        github-token: ${{ secrets.GH_PAT }}

  main:
   needs: start-runner
   runs-on: ${{ needs.start-runner.outputs.instance-id }}
   steps:
     - run: uname -a

  stop-runner:
    if: always()
    needs: [start-runner, main]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Terraform code
      uses: actions/checkout@v2
      with:
        repository: andycockers/hcloud-actions-runner
        token: ${{ secrets.GH_PAT }}
        path: hcloud-actions-runner
    - name: Stop runner
      uses: andycockers/hcloud-actions-runner/stop@v0.0.38
      with:
        instance-id: ${{ needs.start-runner.outputs.instance-id }}
        hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
