name: hcloud server test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'terraform/modules/hcloud_server/**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - id: runner
        name: Start runner
        uses: andycockers/hcloud-actions-runner/start@0.0.2
        with:
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          type: type=github-hcloud-runner
          server_type: cx11
          location: fsn1
          network_id: "823122"
          github-token: ${{ secrets.GH_PAT }}
    outputs:
      instance-id: ${{ steps.runner.outputs.instance-id }}

   main:
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.instance-id }}
    steps:
      - run: uname -a