name: hcloud test cli

on:
  
  workflow_dispatch:
jobs:
  start-runner:
    runs-on: ubuntu-latest
    outputs:
      instance-id: ${{ steps.runner.outputs.instance-id }}
    steps:
    - id: runner
      name: Start runner
      uses: andycockers/hcloud-actions-runner/start-cli@v0.0.54
      with:
        hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        image-id: "55418267"
        server_type: cx11
        location: fsn1-dc14
        network_id: "823122"
        github-token: ${{ secrets.GH_PAT }}

  main:
   needs: start-runner
   runs-on: ${{ needs.start-runner.outputs.instance-id }}
   steps:
     - run: uname -a

  stop-runner:
    if: always()
    needs: [start-runner, main]
    runs-on: ubuntu-latest
    steps:
    - name: Stop runner
      uses: andycockers/hcloud-actions-runner/stop-cli@v0.0.54
      with:
        instance-id: ${{ needs.start-runner.outputs.instance-id }}
        hcloud_token: ${{ secrets.HCLOUD_TOKEN }}